---
- name: mysql packages
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server-5.7
  register: mysql_installed
  tags: ['mysql']

- name: create log-bin directory
  file: path=/var/lib/mysql/bin_files state=directory owner=mysql group=mysql mode=0700
- name: enable mysql
  service: name=mysql enabled=yes
  tags: ['mysql']

# service start does not work well inside docker container
- name: start mysql
  command: /etc/init.d/mysql start
  when: mysql_installed.changed
  tags: ['mysql']

- name: delay while starting mysql
  wait_for: host=localhost port=3306 delay=10
  tags: ['mysql']

- name: mysql db
  shell: /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e 'create database korjournal'
  register: create_db
  ignore_errors: yes
  tags: ['mysql']

- name: mysql user
  shell: /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e "create user 'korjournal'@'%' identified by 'ReplaceDevPwd'"
  when: create_db.rc == 0
  ignore_errors: yes
  tags: ['mysql']

- name: mysql perms
  shell: /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e "grant all privileges on korjournal.* to 'korjournal'@'%'"
  when: create_db.rc == 0
  ignore_errors: yes
  tags: ['mysql']

- name: block outside access to mysql
  shell: iptables -I INPUT -i eth0 -p tcp --dport 3306 -j DROP
  when: create_db.rc == 0
  ignore_errors: yes
  tags: ['mysql']

- name: my.cnf
  template:
    src: mycnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
  tags: ['mysql']
