# Creates or destroys a DO droplet
- name: Start droplet
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Start or Terminate
      local_action:
        module: digital_ocean
        state: '{{ droplet_state }}'
        command: droplet
        name: 'korjournal-dev'
        unique_name: yes
        size_id: 1gb
        region_id: ams2
        private_networking: yes
        image_id: ubuntu-16-04-x64
        ssh_key_ids: [ 1898821 ]
        wait: yes
      register: digocn
      tags: [inventory]
    - debug:
        var=digocn
      tags: [inventory]

    - name: Add all instances to inventory
      local_action: add_host name={{ digocn.droplet.networks.v4[1].ip_address }} groupname=digocn
      when: droplet_state == "present"
      tags: [inventory]

    - name: Wait for SSH to come up on all instances
      local_action: wait_for host={{ digocn.droplet.networks.v4[1].ip_address }} port=22 delay=3 timeout=420 state=started
      when: droplet_state == "present"

- name: Bootstrap instances
  hosts: digocn
  user: root
  sudo: false
  gather_facts: False
  tasks:
    - name: Check if bootstrap is needed
      raw: stat /root/.bootstrapped
      register: need_bootstrap
      ignore_errors: True

    - name: Run bootstrap
      raw: apt-get -y install python
      when: need_bootstrap | failed

    - name: Finish bootstrap
      shell: python -c 'fhandle = open("/root/.bootstrapped","a")'

- name: Make ready for deploy
  hosts: digocn
  user: root
  sudo: false
  gather_facts: False
  roles:
    - mysql
    - docker
    - secrets
    - webapp
